<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

    <form action="index.php" method="POST">
        <label for="language">choose language:</label>
        <select name="language" id="">
            <option value="ru"><?= $language['ru'] ?></option>
            <option value="en"><?= $language['en'] ?></option>
            <option value="ua"><?= $language['ua'] ?></option>
        </select>

        <label for="email">enter email: </label>
        <input type="email" name="email">

        <label for="phone">enter phone: </label>
        <input type="phone" name="phone">
        
        <label for="password">enter password: </label>
        <input type="password" name="password">

        
        <button type="sybmit">klac</button>
    </form>

    <div>
        <span>email: <?= $email ?></span> 
        <span>phone: <?= $phone ?></span>
        <span>password: <?= $password ?></span>
    </div>

    <a href="index.php" id='clear'>clear</a>
</body>
</html>