<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

<div class="form-validation">
    <form action="homeworkLMS/lms10/register.php" method="post" style="display:flex; justify-content: center; margin-top: 200px;">
        <label for="login">Login:</label>
        <input type="text" name="login" placeholder="введите логин">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="введите пароль">

        <input type="submit" value="registration">
    </form>
</div>


</body>
</html>